<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Order_model extends CI_Model
{

    public $table = 'tb_order';
    public $id = 'id_order';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_order', $q);
	$this->db->or_like('id_product', $q);
	$this->db->or_like('referal', $q);
	$this->db->or_like('tgl_order', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_order', $q);
	$this->db->or_like('id_product', $q);
	$this->db->or_like('referal', $q);
	$this->db->or_like('tgl_order', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    public function getProduct(){
        return $this->db->get('tb_product')->result_array();
    }

    public function getCode($code){
        if ($this->db->get_where('tb_user',array('referal' => $code))->num_rows() > 0) {
            return true;
            exit();
        }
        return false;
    }

}

/* End of file Order_model.php */
/* Location: ./application/models/Order_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-02-19 05:58:24 */
/* http://harviacode.com */